name: my_recipes
description: A recipe aggregator and viewer
publish_to: 'none'

version: 0.4.0+5

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0+2
  format: ^1.4.0
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  mobx: ^2.3.0+1
  mobx_codegen: ^2.6.0+1
  url_launcher: ^6.2.3
  uuid: ^4.2.2
  html_recipe_parser:
    git:
      url: https://github.com/eggnogdev/html_recipe_parser.git
      ref: 0.3.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  http: ^1.2.0
  wakelock_plus: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#004C6C"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
